### PR TITLE
判断 content_type 更全面

### PR DESCRIPTION
**Pull request by zhuangsirui**
照着 `mailgun` 的一个 `gem` 包加了点判断。

### CODE REVIEW

**Comment by emn178** [comment]
Hi, could you help to add some unit tests for this? thanks.

**Comment by zhuangsirui** [comment]
@emn178 I will add some unit test at weekend.

**Comment by emn178** [comment]
great!

**Comment by zhuangsirui** [comment]
@emn178 So sorry. I'v been busy last weekend. I will add the unit test tonight.

**Pull request merged**
